### ISSUE TITLE
[solved] noto characters in PDF that are not related to actual content (probably just style related), how do I change it?

### ISSUE THREAD

**Issue by eladkarako** [eugmes/fntsample#31]
here is an example
`arial.ttf`  
[arial.ttf.zip](https://github.com/eugmes/fntsample/files/9443810/arial.ttf.zip)

`arial.ttf.pdf`
[arial.ttf.pdf.zip](https://github.com/eugmes/fntsample/files/9443809/arial.ttf.pdf.zip)

<img src="https://user-images.githubusercontent.com/415238/187182399-c4765dec-9907-49c5-97db-dcafd4e2c91e.png">

<hr/>

running on Cygwin,  
which relay on `C:\Windows\Fonts\` for actual having other fonts 
I've edited `C:\cygwin\etc\fonts\fonts.conf`

```diff
<!-- Font directory list -->

+<dir>/cygdrive/C/Windows/Fonts</dir>
+<dir>C:/Windows/Fonts</dir>
+<dir>/usr/share/fonts</dir>
```

[fonts.zip](https://github.com/eugmes/fntsample/files/9443837/fonts.zip)

and then the result was looking fine,  

<img src="https://user-images.githubusercontent.com/415238/187183649-0bef9858-4bb3-42fb-99b5-4ba943548270.png">

<hr/>

my suggestion/question is,  
how to control, what I assume is a hard-codded styling for the PDF,  

or an ability to control the non-critical presentation layer of the PDF,  
either of those would be greatly appreciated.

**Comment by eugmes** [comment]
Hi, the fonts for the tables are not hardcoded, but they do need to be installed (you cannot just specify a font file for them). You can change those fonts using ``--style`` option. Here are the defaults for various styles (as shown when ``--help`` is supplied):

```
	header-font (Sans Bold 12)
	font-name-font (Serif Bold 12)
	table-numbers-font (Sans 10)
	cell-numbers-font (Mono 8)
```

You can change the header font like this:

```
    fntsample --style "header-font: Arial 14" ....
```

**Comment by eladkarako** [comment]
thank you!  
that is what I was missing!
