### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by usharf** [eugmes/fntsample#8]
I'm assuming `fntsample` support utf-8 in the pdfoutline tool? I'm seeing this garbage when trying to create an outline from a txt file (utf-8) with hebrew titles.... both in Linux (Ubuntu) document viewer and Emacs etc.

![screenshot](https://user-images.githubusercontent.com/1701421/33656734-43b40bbc-da77-11e7-83c7-329709f37178.png)

**Comment by eugmes** [comment]
There was no special support for non-ascii characters in the library used by pdfoutline. This should be fixed now. Please let me know if the problem is fixed for you.

**Comment by usharf** [comment]
I've tested it with `pdftk` _utf8 version of the actions to import and export meta data, and it works fine. Is this what you're refering to?

**Comment by eugmes** [comment]
There is no ppa, in fact the fixed version is not release jet, but you can download pdfoutline.pl from here https://raw.githubusercontent.com/eugmes/fntsample/master/pdfoutline.pl, and test it by running `perl pdfoutline.pl <other args>`. I'll make a new Debian release shortly after some more testing. I'm not using Ubuntu, so I'm not maintaining any ppa.

**Comment by usharf** [comment]
Oh yes. I was actually just looking at it. I remberer installing it as part of a package, so didn’t pay atttention. Will test and report.

**Comment by usharf** [comment]
Works!

**Comment by eugmes** [comment]
Great! Thanks for testing.
